---
# tasks file for apache
- name: Install apache
  apt:
    name: apache2
    state: latest
  
- name: config apache
  template:
    src: apache2.conf.j2
    dest: /etc/apache2/apache2.conf
  notify: restart apache
  